"""timezone_and_constraints

Revision ID: 6c567eb6f930
Revises: 
Create Date: 2026-06-08 09:15:29.576369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c567eb6f930'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('friendships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('friendships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint('uq_friendship_pair', 'friendships', ['requester_id', 'addressee_id'])
    op.drop_constraint('friendships_requester_id_fkey', 'friendships', type_='foreignkey')
    op.drop_constraint('friendships_addressee_id_fkey', 'friendships', type_='foreignkey')
    op.create_foreign_key(None, 'friendships', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friendships', 'users', ['addressee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('game_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('game_invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('game_invitations_inviter_id_fkey', 'game_invitations', type_='foreignkey')
    op.drop_constraint('game_invitations_invitee_id_fkey', 'game_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'game_invitations', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game_invitations', 'users', ['invitee_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'reset_token_expires',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token_expires',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'game_invitations', type_='foreignkey')
    op.drop_constraint(None, 'game_invitations', type_='foreignkey')
    op.create_foreign_key('game_invitations_invitee_id_fkey', 'game_invitations', 'users', ['invitee_id'], ['id'])
    op.create_foreign_key('game_invitations_inviter_id_fkey', 'game_invitations', 'users', ['inviter_id'], ['id'])
    op.alter_column('game_invitations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('game_invitations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.drop_constraint(None, 'friendships', type_='foreignkey')
    op.create_foreign_key('friendships_addressee_id_fkey', 'friendships', 'users', ['addressee_id'], ['id'])
    op.create_foreign_key('friendships_requester_id_fkey', 'friendships', 'users', ['requester_id'], ['id'])
    op.drop_constraint('uq_friendship_pair', 'friendships', type_='unique')
    op.alter_column('friendships', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('friendships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
